#!/usr/bin/env bash
# Configuring domain zone so that the subdomain www points to lb
doma () {
dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ]
then
    doma "$2.$1" "$2"
else
    doma "www.$1" "www"
    doma "lb-01.$1" "lb-01"
    doma "web-01.$1" "web-01"
    doma "web-02.$1" "web-02"
fi
