#!/usr/bin/env bash
#install nginx on web-01
apt-get -y update
apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx restart
