#!/usr/bin/env bash
#custom header
sudo apt-get -y update
sudo apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
sudo sed -i "1i add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
service nginx restart
