#!/usr/bin/env bash
#custom header
sudo apt-get -y update
sudo apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default
sudo sed -i "21i add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
service nginx restart
