#!/usr/bin/env bash
# haproxy
apt-get install -y software-properties-common
sudo apt-get -y update
sudo add-apt-repository ppa:vbernat/haproxy-2.4 -y
sudo apt-get install -y haproxy=2.4.\*
echo "ENABLED=1" > /etc/default/haproxy
echo "listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 474016-web-01 34.204.101.190:80 check
   server 474016-web-02 100.25.197.195:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy start
