#!/usr/bin/python3
""" return number of subs in subreddit """
import requests


def number_of_subscribers(subreddit):
    """ return number of subs in subreddit """
    user = {'User-Agent': 'noted'}
    url = requests.get('https://www.reddit.com/r/{}/about.json'
                       .format(subreddit), headers=user).json()
    try:
        return url.get('data').get('subscribers')
    except Exception:
        return 0


if __name__ == "__main__":
    number_of_subscribers(argv[1])
