#!/usr/bin/env bash
#fizzbuzz
index=1
while [ $index -ne 101 ]
do
	if [ $((index % 5)) -eq 0 ]
	then
		echo "Buzz"
	elif [ $((index % 3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((index % 15)) -eq 0 ]
	then
		echo "FizzBuzz"
	else
		echo $index
	fi
	((index++))
done
