#!/usr/bin/env bash
#task 5
COUNT=1
while [ $COUNT -ne 11 ]
do
	if [ $COUNT -eq 4 ]; then
		echo "bad luck"
	elif [ $COUNT -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((COUNT++))
done
